test1:
	raco test ex1-1.rkt ex1-2.rkt ex1-3.rkt ex1-7a.rkt ex1-7b.rkt ex1-8.rkt
test2:
	raco test ex1-10.rkt ex1-11.rkt ex1-12.rkt
test3:
	raco test ex1-16.rkt ex1-17.rkt ex1-18.rkt ex1-19.rkt

#test4:
#	raco test ex1-20.rkt ex1-21.rkt ex1-22.rkt ex1-23.rkt ex1-24.rkt ex1-25.rkt ex1-26.rkt ex1-27.rkt ex1-28.rkt ex1-29.rkt

test5:
	raco test ex1-30.rkt ex1-31.rkt ex1-32.rkt ex1-34.rkt
test6:
	raco test ex1-35.rkt ex1-36.rkt ex1-37.rkt ex1-38.rkt ex1-39.rkt

testproject:
	raco test simple-integration.scm calculus.scm

all: test1 test2 test3 test5 test6 testproject
